ZSH=$HOME/.oh-my-zsh
ZSH_THEME="wangyuhere"
DISABLE_AUTO_UPDATE="true"

plugins=(git brew vi-mode heroku rails3 bundler wangyuhere)

export PATH="/usr/local/Cellar/go/1.1.2/bin:/usr/local/sbin:/usr/local/bin:$PATH"
export EDITOR="st -w"

source $ZSH/oh-my-zsh.sh

if which rbenv > /dev/null; then
  eval "$(rbenv init -)"
fi

export GOPATH=$HOME/Projects/go
export PATH="$GOPATH/bin:$PATH"
export LANG=sv_SE.UTF-8

export RUBY_HEAP_MIN_SLOTS=2000000
export RUBY_HEAP_FREE_MIN=20000
export RUBY_GC_MALLOC_LIMIT=100000000
